"""GTIN candidate selection and multi-panel deduplication.

Resolves the primary candidate GTIN from a BarcodeSummary by:
1. Filtering out 2D carriers (e.g., QR Code, Data Matrix).
2. Requiring structural and check-digit validity (is_valid_gtin == True).
3. Deduplicating identical GTIN values appearing across multiple packaging panels.
4. Preserving genuine ambiguity when multiple distinct valid GTINs exist.
"""

from typing import List, NamedTuple, Optional, Set

from backend.app.schemas.barcode import BarcodeFormat, BarcodeItem, BarcodeSummary
from backend.app.schemas.gtin_identity import GTINLookupStatus


class GTINSelectionResult(NamedTuple):
    """Outcome of GTIN candidate resolution."""

    selected_gtin: Optional[str]
    status: GTINLookupStatus
    message: str
    unique_candidates: List[str]


# 2D symbologies typically used for marketing, URLs, or internal tracking
NON_RETAIL_CARRIER_FORMATS = {
    BarcodeFormat.QR_CODE,
    BarcodeFormat.DATA_MATRIX,
}


def select_gtin_candidate(barcode_summary: Optional[BarcodeSummary]) -> GTINSelectionResult:
    """Select and deduplicate a primary GTIN candidate from decoded barcodes.

    Args:
        barcode_summary: The BarcodeSummary generated by BarcodeService.

    Returns:
        GTINSelectionResult indicating the selected GTIN or ambiguity/absence.
    """
    if not barcode_summary or not barcode_summary.detected or not barcode_summary.barcodes:
        return GTINSelectionResult(
            selected_gtin=None,
            status=GTINLookupStatus.NO_GTIN_DETECTED,
            message="No barcode detected on submitted package image(s).",
            unique_candidates=[],
        )

    # Filter out 2D carriers and non-valid GTINs
    eligible_items: List[BarcodeItem] = []
    has_invalid_gtin = False

    for item in barcode_summary.barcodes:
        if item.format in NON_RETAIL_CARRIER_FORMATS:
            continue
        if item.gtin and not item.is_valid_gtin:
            has_invalid_gtin = True
        if item.is_valid_gtin and item.gtin:
            eligible_items.append(item)

    if not eligible_items:
        if has_invalid_gtin:
            return GTINSelectionResult(
                selected_gtin=None,
                status=GTINLookupStatus.INVALID_GTIN,
                message="Detected barcode(s) had invalid GTIN structure or check digit.",
                unique_candidates=[],
            )
        return GTINSelectionResult(
            selected_gtin=None,
            status=GTINLookupStatus.NO_GTIN_DETECTED,
            message="No retail 1D barcode with a valid GTIN was detected.",
            unique_candidates=[],
        )

    # Deduplicate by GTIN string across panels (preserving discovery order)
    seen_gtins: Set[str] = set()
    unique_gtins: List[str] = []
    for item in eligible_items:
        g = item.gtin.strip()
        if g not in seen_gtins:
            seen_gtins.add(g)
            unique_gtins.append(g)

    # Exactly one unique valid GTIN
    if len(unique_gtins) == 1:
        resolved = unique_gtins[0]
        panels = [item.panel_label for item in eligible_items if item.gtin == resolved and item.panel_label]
        panels_info = f" (sighted on: {', '.join(panels)})" if panels else ""
        return GTINSelectionResult(
            selected_gtin=resolved,
            status=GTINLookupStatus.FOUND,
            message=f"Single valid GTIN resolved: {resolved}{panels_info}.",
            unique_candidates=unique_gtins,
        )

    # Multiple distinct valid GTINs: preserve ambiguity
    return GTINSelectionResult(
        selected_gtin=None,
        status=GTINLookupStatus.AMBIGUOUS_GTIN,
        message=(
            f"Multiple distinct valid GTINs detected on package ({len(unique_gtins)} candidates: "
            f"{', '.join(unique_gtins)}). Ambiguity preserved without arbitrary selection."
        ),
        unique_candidates=unique_gtins,
    )
